version: '3.8'

services:
  solara:
    build: .        
    container_name: solara
    restart: always
    init: true
    ports:
      - "8080:8787"
    environment:
      - PASSWORD=       # 在这里填上你的登录密码
      - API_BASE_URL=https://music-api.gdstudio.xyz/api.php
      # - language=ENG
    volumes:
      - ./data:/data    # 持久化数据库，冒号两边不要写错！！